### ISSUE TITLE
[RFE][UX] Check if KubeVirt is installed (or not)

### ISSUE THREAD

**Issue by vatsalparekh** [ansibleplaybookbundle/import-vm-apb#19]
while importing a VM via apb from console, we should check if the KubeVirt is installed or not, and maybe enforce installing it first, because without it we know importing will fail

**Comment by vatsalparekh** [comment]
@pkliczewski

**Comment by pkliczewski** [comment]
@rthallisey What do you think?

**Comment by rthallisey** [comment]
@pkliczewski @vatsalparekh makes sense to check before hand.  Maybe we can curl the kubevirt api and see if we get a response?

**Comment by vatsalparekh** [comment]
@rthallisey agree, suggestion here was if we can include it as part of APB itself and notice if its not installed.

**Comment by rthallisey** [comment]
> @rthallisey agree, suggestion here was if we can include it as part of APB itself and notice if its not installed.
>
By "it", are you saying the templates that make up kubevirt?

**Comment by vatsalparekh** [comment]
@rthallisey I meant the check to see if kubevirt is there or not, as part of the APB

**Comment by rthallisey** [comment]
ack.  I think we're on the same page.
