### ISSUE TITLE
Initial UX review

### ISSUE THREAD

**Issue by aglitke** [ansibleplaybookbundle/import-vm-apb#2]
Please review the UX of the current implementation.  So far only Import from URL is implemented.

![01](https://user-images.githubusercontent.com/333311/38110643-4f89c7f0-336a-11e8-9a95-0a15a65cc9c2.png)
![02](https://user-images.githubusercontent.com/333311/38110648-5245ed16-336a-11e8-8699-5520d2af7695.png)
![3a](https://user-images.githubusercontent.com/333311/38110653-54a145b0-336a-11e8-9eba-44a285665a09.png)
![3b](https://user-images.githubusercontent.com/333311/38110656-56df70ea-336a-11e8-911e-c94767ae3f99.png)

**Comment by xsgordon** [comment]
This is minor quibble but s/VMWare/VMware/

I assume we ask for the pass twice because if they get it wrong we go too far down the rabbit hole to throw an error?

**Comment by pkliczewski** [comment]
Here is the screen when vmware plan is selected:

![import-vm-vmware-screen](https://user-images.githubusercontent.com/1384786/38136448-a2090b3a-341e-11e8-9bea-6b09e9a6053a.png)

**Comment by rthallisey** [comment]
@xsgordon yes.  This functionality is build into the UI.

**Comment by beanh66** [comment]
@aglitke Thanks for providing the screenshots! As requested, I created separate issues for things that need to be updated or resolved.
