### ISSUE TITLE
VM Pod details in the Provisioned Services UI

### ISSUE THREAD

**Issue by vatsalparekh** [ansibleplaybookbundle/import-vm-apb#20]
After filling apb to import a VM, there are no VM related pod details shown in provisioned services UI, so in case of importing multiple VMs, one simply cannot find which pod is for which VM to see logs or any such stuff.

**Comment by vatsalparekh** [comment]
@pkliczewski @rthallisey

**Comment by pkliczewski** [comment]
@rthallisey I am not aware of any mechanism we could use to provide to the user. In this case there was no kubevirt and import failed. Is there a way to present additional info on the UI?

**Comment by rthallisey** [comment]
> After filling apb to import a VM, there are no VM related pod details shown in provisioned services UI, so in case of importing multiple VMs, one simply cannot find which pod is for which VM to see logs or any such stuff.
>
KubeVirt launches the pod and does the naming.  Might be a good issue to bring up there.

**Comment by rthallisey** [comment]
> @rthallisey I am not aware of any mechanism we could use to provide to the user. In this case there was no kubevirt and import failed. Is there a way to present additional info on the UI?
>
You're talking about when an APB fails?  We can use the last_operation endpoint to provide logging to the UI while it's running.  If you want to capture specific error messages see https://www.youtube.com/watch?v=GiJrTX05Jno

**Comment by awels** [comment]
@rthallisey I think they are talking about the naming of the provisioned services. If you import multiple VMs (or templates for that matter) the provisioned service is name 'Import Virtual Machine' with no indication which one is which. So if we from the apb could add something to the name of the provisioned service that would help the user to know which one is related to which VM (or template).

**Comment by vatsalparekh** [comment]
yes @awels , that's what I meant!

**Comment by rthallisey** [comment]
```bash
  name: v2v-job-template
```

The name of the template is v2v-job-template.  You're saying the template created is always 'Import Virtual Machine'?
