### ISSUE TITLE
name change: ovm to virtual machine

### ISSUE THREAD

**Issue by vatsalparekh** [ansibleplaybookbundle/import-vm-apb#31]
in current apb, when importing a vm via url, the form shows 2 options `ovm` and `template`
with the latest changes in kubevirt, `ovm` should be changed to `virtual machine`

**Comment by vatsalparekh** [comment]
cc: @simon3z @nellyc

**Comment by pkliczewski** [comment]
Here is Trello card tracking it https://trello.com/c/4yWKz4UY/117-3-epic-offlinevm-rename-v2v-rename-of-vm-entity

**Comment by simon3z** [comment]
@vatsalparekh @pkliczewski it's probably nice to keep those with proper capitalization "Virtual Machine", "Template".

**Comment by pkliczewski** [comment]
@simon3z Sure, let's use nice capitalization. Thanks for suggestion.

**Comment by pkliczewski** [comment]
This issue was fixed by https://github.com/ansibleplaybookbundle/import-vm-apb/pull/38
