### ISSUE TITLE
Importing with same name as existing PVC will remove it.

### ISSUE THREAD

**Issue by awels** [ansibleplaybookbundle/import-vm-apb#43]
The following scenario will remove an existing PVC, due to the does the PVC exist check (would do the same without the check as it would fail on the binding of the PVC).

1. Someone has a running VM with name: test, and thus has a PVC with name test-disk-01
2. Now I come in and try to create a VM called 'test' using the APB. I fill in all the fields and hit create.
3. The provision step will fail (due to the above mentioned reasons), and thus the de-provision step will fire. This will attempt to delete the VM resources (and ignore not found), and then attempt to delete the PVC with the name test-disk-01, because the names match.

This will remove the PVC from the existing VM, potentially while its running, that cannot be good.

**Comment by pkliczewski** [comment]
cc @aglitke
