### ISSUE TITLE
annotation issue with CDI

### ISSUE THREAD

**Issue by vatsalparekh** [ansibleplaybookbundle/import-vm-apb#44]
Currently we are supposed to be keeping CDI version `0.5` which looks for annotations without `cdi` in prefix here https://github.com/ansibleplaybookbundle/import-vm-apb/blob/master/roles/import-from-url/templates/cdi-pvc.yml#L6
The changes here https://github.com/kubevirt/containerized-data-importer/pull/210 are correct but there should be a separate branch compatible with cdi 0.5 as well

**Comment by pkliczewski** [comment]
cc @aglitke

**Comment by aglitke** [comment]
I think we're planning to cut a stable release based on kubevirt:release-0.6 and an as-yet-unamed cdi stable release that includes host-assisted cloning.  That CDI release will use the updated annotations.

**Comment by vatsalparekh** [comment]
@aglitke @pkliczewski also the phase annotation for importer pod also needs to be aligned, currently apb is looking for `cdi.kubevirt.io` for that as well

**Comment by aglitke** [comment]
@vatsalparekh already fixed by #40.
