### ISSUE TITLE
[RFE] StorageClass field should be a dropdown

### ISSUE THREAD

**Issue by vatsalparekh** [ansibleplaybookbundle/import-vm-apb#51]
The text box to enter `Storage Class` should be a Dropdown option to select from the available storage classes

**Comment by vatsalparekh** [comment]
cc: @aglitke @pkliczewski

**Comment by aglitke** [comment]
This is not possible since the service catalog doesn't provide any means to have a dynamic API.  All fields must be defined at build time in the apb metadata.
