### ISSUE TITLE
"Windows Virtual Machine" APB fails with unknown parameter PVC_NAME

### ISSUE THREAD

**Issue by grafuls** [ansibleplaybookbundle/import-vm-apb#55]
**Is this a BUG REPORT or FEATURE REQUEST?**:
/kind bug

**What happened**:
When following the "Windows Virtual Machine" APB wizard from the catalog, it fails to generate the VM from the template with the following err:

fatal: [localhost]: FAILED! => {"changed": true, "cmd": "oc process -f /tmp/vmtemplate.yaml -pNAME=win2012 -pMEMORY=4096Mi -pCPU_CORES=2 -pPVC_NAME=disk-windows > /tmp/vm.yaml", "delta": "0:00:00.510032", "end": "2018-08-07 12:16:21.193470", "msg": "non-zero return code", "rc": 1, "start": "2018-08-07 12:16:20.683438", "stderr": "error: unknown parameter name \"PVC_NAME\"", "stderr_lines": ["error: unknown parameter name \"PVC_NAME\""], "stdout": "", "stdout_lines": []}

**What you expected to happen**:
VM is created succesfully

**How to reproduce it (as minimally and precisely as possible)**:
Follow the "Windows Virtual Machine" APB wizard from the catalog and input an existing PVC name under the "Pvc to use" field.

**Environment**:
KubeVirt version (use virtctl version):
Client Version: version.Info{GitVersion:"v0.7.0", GitCommit:"b5b91243f540739eb5db61af89b2f1e5ba449dfa", GitTreeState:"clean", BuildDate:"2018-07-04T14:16:40Z", GoVersion:"go1.10", Compiler:"gc", Platform:"linux/amd64"}
Server Version: &version.Info{GitVersion:"v0.7.0", GitCommit:"b5b91243f540739eb5db61af89b2f1e5ba449dfa", GitTreeState:"clean", BuildDate:"2018-07-04T14:16:40Z", GoVersion:"go1.10", Compiler:"gc", Platform:"linux/amd64"}
Kubernetes version (use kubectl version):
Client Version: version.Info{Major:"1", Minor:"10+", GitVersion:"v1.10.0+b81c8f8", GitCommit:"b81c8f8", GitTreeState:"clean", BuildDate:"2018-07-10T22:32:34Z", GoVersion:"go1.9.4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"10+", GitVersion:"v1.10.0+b81c8f8", GitCommit:"b81c8f8", GitTreeState:"clean", BuildDate:"2018-07-10T22:32:34Z", GoVersion:"go1.9.4", Compiler:"gc", Platform:"linux/amd64"}

**Comment by nellyc** [comment]
@xsgordon
are we shipping the win apb?

**Comment by aglitke** [comment]
The windows apb is no longer being maintained.
