### ISSUE TITLE
[RFE] show apb version info in description 

### ISSUE THREAD

**Issue by vatsalparekh** [ansibleplaybookbundle/import-vm-apb#57]
Currently apb doesn't show version info about which apb we are going to run from console.
Description should have version info

**Comment by vatsalparekh** [comment]
cc @rthallisey

**Comment by aglitke** [comment]
Seems like a good idea to me.

**Comment by vatsalparekh** [comment]
@aglitke @pkliczewski 
I am putting a PR for this
I think Version here should also be in sync with the release tags and Version info put in the description
https://github.com/ansibleplaybookbundle/import-vm-apb/blob/v0.7.0/apb.yml#L1

and it would make sense to update this in all the releases, would make it verbose for the user to see which apb he is actually deploying
