### ISSUE TITLE
v2v fails when id given with domain

### ISSUE THREAD

**Issue by vatsalparekh** [ansibleplaybookbundle/import-vm-apb#59]
Passing the vmware login id with `@vsphere.local` results in error where `virsh` is not able to parse it

**Comment by pkliczewski** [comment]
I checked how `virt-v2v` works with this environment and I got:

> Enter username for env-nvc65-vcsa.cfme2.lab.eng.rdu2.redhat.com [administrator]:  administrator@vsphere.local
> Enter administrator@vsphere.local's password for env-nvc65-vcsa.cfme2.lab.eng.rdu2.redhat.com: 
> libvirt: ESX Driver error : internal error: HTTP response code 500 for call to 'Login'. Fault: ServerFaultCode - Cannot complete login due to an incorrect user name or password.

Will ping `virt-v2v` maintainer to understand how to pass username like this.
